version: "3.9"
services:

  api:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./src/:/app
      - ./tests:/tests
      - ./scripts:/scripts
    depends_on:
      - db

  perf-test:
    build:
      dockerfile: locust/Dockerfile.Locust
    ports:
      - 8089:8089
    volumes:
      - ./locust:/locust
    depends_on:
      - db
      - api

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: routes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    depends_on:
      - prometheus
