FROM python:3.9-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src/ .
CMD [ \
    "uvicorn", "main:app"\
]
