FROM python:3.9-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app
COPY requirements.in requirements.in
RUN pip install pip-tools
RUN pip-compile requirements.in > requirements.txt
RUN pip install -r requirements.txt
RUN pip install debugpy -t /tmp
COPY src/ .
CMD [ "python", "/tmp/debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "main.py" ]
