version: "3.9"
services:

  api:
    build:
      dockerfile: Dockerfile.Dev
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./src/:/app
      - ./tests:/tests

  perf-test:
    image: locustio/locust:2.8.3
    command: -f /locust/locustfile.py -H http://api:8000 -u 10 -r 1
    ports:
      - 8089:8089
    volumes:
      - ./locust:/locust

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: routes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080